### ISSUE TITLE
Support 'missing_ok' argument to Platform class without generating warnings

### ISSUE THREAD

**Issue by kfrey-idm** [InstituteforDiseaseModeling/idmtools#1655]
My use of Platform (from idmtools.core.platform_factory) involves specifying parameters as arguments as much as possible and not relying on the idmtools.ini file. Right now I have a lot of examples where I specify 'block' as an argument, and my ini-file is quite minimal.

Example (the second code block is the entirety of my idmtools.ini file):
```
# Connect to COMPS
plat_obj = Platform(block        = 'COMPS',
                    endpoint     = 'https://comps.idmod.org',
                    environment  = 'Calculon')
```
```
[COMPS]
type = COMPS
```

It would be _really_ nice if the Platform class could take 'type' as an argument rather than requiring the idmtools.ini file.

**Comment by kfrey-idm** [comment]
Wanted to refresh/update this one for v1.7.5:

- The `type` argument is never consumed and ignored. Including it will generate a warning:
```
/!\ WARNING: The following User Inputs are not used:
 - type = COMPS
```

- The `block` argument is a required positional argument for the Platform class. (There is also a ValueError if I try setting it to `None`)

- If I set `block = 'COMPS'` and `missing_ok = True` then I get the behavior I want, but with warnings:
```
/!\ WARNING: File 'idmtools.ini' Not Found! For details on how to configure idmtools, see https://docs.idmod.org/projects/idmtools/en/v1.7.5/configuration.html for details on how to configure idmtools.
You are specifying a platform without a configuration file or configuration block. Be sure you have supplied all required parameters for the Platform as this can result in unexpected behaviour. Running this way is only recommended for development mode. Instead, it is recommended you create an idmtools.ini to capture the config once you have tested and confirmed your configuration.
```

I would like to get the behavior in the third bullet (`block = 'COMPS'` and `missing_ok = True` ), but without generating the warning for missing configuration file and the warning for development mode.

**Comment by jps1** [comment]
I agree with @kfrey-idm.  I would prefer behavior like:

* If `block` argument is specified, attempt to load that section; if idmtools.ini doesn't exist or the specified block doesn't exist in it, throw an error.
* Combine configuration from any specified `block` and arguments passed directly to the Platform() constructor.  If any arguments have been specified twice or any required arguments haven't been specified at all, throw an error (could just do a warning for args specified twice and have one of the two methods override, probably constructor, but is there any reason to want to support this behavior...?)
* Get rid of the `missing_ok` parameter completely.

@ZDu-IDM / @shchen-idmod what do you think about that proposal?  Any thoughts/concerns?

**Comment by shchen-idmod** [comment]
I believe we can resolve all these outstanding issues, but it's not as simple as changing a few lines of code. There are many areas that require adjustments and thorough testing.

We want to ensure that these cases function properly without idmtools.ini and without generating any warning messages:
-  Platform(block='COMPS', endpoint = 'https://comps.idmod.org', environment = 'Calculon', type='COMPS')
**old behavior: warning on idmtools.ini not found and ERROR: ValueError: Block 'COMPS' doesn't exist**! 
- Platform(block='COMPS', endpoint = 'https://comps.idmod.org', environment = 'Calculon') --no need type
**old behavior: warning on idmtools.ini not found and ERROR: ValueError: Block 'COMPS' doesn't exist!** 
- Platform(block="Calculon")
**old behavior: warning on idmtools.ini not found**
- Platform("Calculon")
**old behavior: warning on idmtools.ini not found**
- If there is idmtools.ini file and there is block PROD_COMPS

**[COMPS]
type        = COMPS
endpoint    = https://comps.idmod.org
environment = Calculon
Platform(block="PROD_COMPS")** --should work

Following should throw error or warning (assume no idmtools.ini):
- Platform(block='COMPS1', endpoint='https://comps.idmod.org',  environment='CALCULON')
**New behavior: COMPS1 is an unknown Platform Type
Old behavior: ValueError: Block 'COMPS1' doesn't exist!**

- with Platform(block='COMPS', endpoint = 'https://comps.idmod.org', environment = 'Calculon', type2="test")
**Old behavior: WARNING: The following User Inputs are not used: type2 = test
New behavior: should be the same as old**

-  Platform("Calculon", endpoint = 'https://comps.idmod.org', environment = 'Calculon', missing_ok=True)
**WARNING: The following User Inputs are not used: missing_ok=True
Old behavior: run ok except maybe no idmtools.ini warning**

- Make sure ssmt and analyzer works with above 5 cases. Also need to make sure new old with old ssmt image works as well.
- 
For missing_ok parameter, we should still set to None but give warning if provided and treat like other unused inputs. Other wise it is signature change, may affect lot of existing scripts

**Comment by ZDu-IDM** [comment]
Thanks @jps1 for the investigation and new proposal to fix this Platform creation issue.

Before diving into resolution, let's recall the workflow involved in creating a Platform:

`platform = Platform(block: str, missing_ok = None, **kwargs)`

The block parameter serves a single purpose: to determine the type of Platform.

**Note**: platform parameters are determined by combining INI and Platform inputs.


Based on user feature requests, the current implementation of block has been enhanced to play three roles (in order):

1. INI File Section Check: If the block matches a section in the INI file, retrieve the type from the specified section.

2. Platform Alias Check: If the block does not match an INI file section, it is used as a platform alias to check available platform types. If found, retrieve the type from the pre-defined platform specifications.

3. Platform Type: If neither of the above conditions are met and missing_ok is set to True, the block is used directly as the platform type.

We need to maintain this workflow, with the following changes:

- Remove the missing_ok parameter.
- Log process information to a file instead of printing it on the screen.

In general, we agree with Jeff's proposal but with some additional considerations for the three roles of the block parameter:

1. Consider the three roles of block and throw exceptions as needed.

2. Our current implementation combines INI and Platform inputs with the following priority:

   (1) Platform, (2) INI, (3) Default 

    We need to handle logging and exception handling more carefully.

3. We need to remove the missing_ok parameter.

By addressing these points, we can ensure a robust and user-friendly implementation.

**Comment by kfrey-idm** [comment]
Thank you! This item is really key for me:
> * Log process information to a file instead of printing it on the screen.

When I collaborate with students that aren't familiar with the tools, I really want avoid generating warnings printed to standard out. (Logs are fine.)

**Comment by ZDu-IDM** [comment]
Thanks @jps1  for continuing the discussion about the three roles of block. We all concur that the third role (block serves as Platform type) is strange and sometimes misleading for the user. We allow this in the current implementation but with a warning: 

**"You are specifying a platform without a configuration file or configuration block. Be sure you have supplied all required parameters for the Platform as this can result in unexpected behavior. Running this way is only recommended for development mode. Instead, it is recommended you create an idmtools.ini to capture the config once you have tested and confirmed your configuration."** 

We think a better approach would be to eliminate this third role and give the user more flexibility to specify Platform type in the Platform constructor.

**New Idea: Handle the Third Case**

We will simplify the block parameter to handle only the first two roles. The block will never be used as a platform "type". Here’s the new approach:

1. Block as INI File Section: If the block matches a section in the INI file, retrieve the type from the specified section.

2. Block as Platform Alias: If No INI file or the block not match in INI file section, it is used as a platform alias to check available platform types. If found, retrieve the "
type" from the pre-defined platform specifications.

If neither of these conditions are met, the Platform constructor will be the fallback location to look for the "type" from user inputs. If the "type" is not found in the Platform constructor, an exception will be thrown.

**Implementation Changes**

- Platform constructor: Set the default value of block to None, making it optional.
- If block is provided, handle the first two roles.
- If block is None, look for the "type" in the Platform constructor. If not found, throw an exception.

**Benefits of This Design**

- Consistency: The block always acts as a 'block' or alias, eliminating any confusion about it being a platform type.
- Clarity: There is a clear distinction between the block roles and the Platform constructor’s responsibility.
- Flexibility: Users can choose to provide inputs via the INI file or directly through the Platform constructor.

**Revised Code Snippet**

```
platform = Platform(block: str = None, **kwargs)

if block:
    # Handle first two roles of block
    if block in ini_file_sections:
        type = get_type_from_ini(block)
    elif block in platform_aliases:
        type = get_type_from_alias(block)
    else:
        # Handle type retrieval from Platform constructor
        type = kwargs.get('type')
        if not type:
           raise Exception("Type must be specified in Platform constructor")
else:
    # Handle type retrieval from Platform constructor
    type = kwargs.get('type')
    if not type:
        raise Exception("Type must be specified in Platform constructor")

# Proceed with the rest of the initialization
```


By following this approach, we ensure a streamlined and user-friendly workflow for creating a Platform.


**Note**, we still need to handle the printout:
- Log process information to a file instead of printing it on the screen.

**Comment by jps1** [comment]
@ZDu-IDM I like that new approach!  Much easier to understand than the old way.
