### ISSUE TITLE
Adjust the default 'max_running_jobs' in SlurmPlatform

### ISSUE THREAD

**Issue by ZDu-IDM** [InstituteforDiseaseModeling/idmtools#2172]
Currently 'max_running_jobs' has default value 1, we should make some adjustments based on simulation count and 'max_array_size'

**Comment by jps1** [comment]
Sharon is going to do some further investigation.
Tentative suggested default: 1000

**Comment by shchen-idmod** [comment]
If the user does not specify max_running_jobs in the platform creation or experiment.run, it defaults to 1. This means that only one simulation will run per job at a time. However, users can adjust max_running_jobs to a higher value if needed.

It's important to choose this default value carefully. since we define slurm array job like "-- array batch_size%max_running_jobs" which mean we can run max_running_job at same time. But this does not mean we want to make max_running_jobs at much as possible. 

Currently batch_size we set can be min(MaxArraySize, total_sim_count) if user does not define array_batch_size in platform. The default MaxArraySize for Slurm is 1000, so batch_size can be1000. If we set default max_running_jobs=1000 as well, they could potentially run 1000 jobs simultaneously. This setup might work well if each simulation is lightweight. However, if the simulations are resource-intensive, this could lead to a significant strain on the cluster's resources, such as CPUs, memory, and other I/O capabilities. This not only degrades the performance of the simulations but may also result in longer wait times for other users in shared resource environment. Additionally, some Slurm cluster might lower the priority of jobs that consume large amounts of resources or require users to wait for a substantial block of resources to become available.

Therefore, I feel like we could set the default max_running_jobs to a more manageable number like 10 or 20. This allows users to scale up based on the resource intensity of their simulations. It is also crucial to document how to adjust this setting clearly. Currently, understanding all available Slurm parameters can be challenging without referring to examples or detailed documentation, especially when user start to type code like platform=Platform("Slurm_Local", max_running_jobs, ...). Proper documentation will help users make informed decisions about configuring their job submissions.
