### ISSUE TITLE
idmtools-test fails because hasn't been released with updated changes while other idmtools have

### ISSUE THREAD

**Issue by stitova-idm** [InstituteforDiseaseModeling/idmtools#2301]
**Table of Contents**

    - [Description]
    
 file_contents_to_generator function has been renamed file_content_to_generator, and though it's been updated in idmtoold-test's code, that code has not been released. I am running into this error. 
    
https://github.com/InstituteforDiseaseModeling/idmtools/blob/12e596ee2385953f81c2a667e820854be4d55c73/idmtools_test/idmtools_test/utils/execute_operations/experiment_operations.py#L17
    
![image](https://github.com/InstituteforDiseaseModeling/idmtools/assets/16845361/ca1c7906-6102-4f2a-8da6-ddc91096f252)
![image](https://github.com/InstituteforDiseaseModeling/idmtools/assets/16845361/885fd313-f33c-4766-9653-c3f4c144b393)

    - [What I Did](#what-i-did)
I installed emodpy-malaria (pip install emodpy-malaria --index-url=https://packages.idmod.org/api/pypi/pypi-production/simple) , 
navigated to examples/create_demographics.py and tried to run it with "python example.py"
I get the error above. I confirmed that all my code is up to date (re-installed all of idmtools), but it looks like code is not insync with itself. 

- [Extras](#extras)

### Description

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

# Extras

Please populate system information by running `idmtools info system --issue`. To accomplish this, please follow these steps
* Ensure *idmtool-cli* packages is installed. You can do this be installing it using the command
```bash
> pip install idmtools-cli --index-url=https://packages.idmod.org/api/pypi/pypi-production/simple
```
* Run
```bash
> idmtools info system --issue
```
This will copy the system information to your clipboard
* Paste the data here

**Comment by stitova-idm** [comment]
NEVERMIND. looks like its my own personal problem. I have no idea what happened.

**Comment by stitova-idm** [comment]
Sharon found issue that was uncovered with this issue: 
Since idmtools_test defined "idmtools_platform" entrypoints as goup and one of them is that util function. so idmtools code will go through all entry points installed in your VM and load import if matched

**Comment by shchen-idmod** [comment]
Thanks @stitova-idm for reporting this issue. I can repro it with mismatch idmtools_test version 1.7.9 and idmtools 1.7.10
The issue is when platform gets created via platform=Platform("calculon"), it loads all the plugin modules from installed VM package list with matched group name "idmtools_platform" and entrypoint name.

Since idmtools_test has entrypoint group "idmtools_platform"  defined in setup.py, it will load all related models by plugin loader(i.e go through all import statements). It will eventually call:
`from idmtools.utils.file import file_contents_to_generator` in idmtools_tests.utils.experiment_operations.py. but there is no file_contents_to_generator anymore for idmtools 1.7.10. So it will throw error.

The workaround is to install the same version of "idmtools_test" and "idmtools" packages(either both >=1.7.10 or both <1.7.10)
For most case, users do not need to install idmtools_test so no issue at all. Only for some automation, you may see this issue. we suggest to pip install --upgrade idmtools_test>=1.7.10 if you really need one. If you do not need it, you can pip uninstall old version of idmtools_test.
